name: Acquire Activation File

on:
  workflow_dispatch: {}

jobs:
  activation:
    name: Request activation file
    runs-on: ubuntu-latest
    steps:
      - uses: game-ci/unity-activate@v2
        id: getManualLicenseFile
        with:
          unityVersion: 6000.0.71f1

      - uses: actions/upload-artifact@v4
        with:
          name: unity-activation-file
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
